name: deploy to Local miki-kube 
on:
  push:
    branches: [ test ]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m        
   - name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t  cicdapplication/devops-challenge_web:v1.
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube
      run:
        kubectl applyy -f /django 
    - name: Test service URLs
      run: |
        kubectl get pods        
